version: "3.8"

# Services
services:
  # Database - MySQL
  db:
    image: mysql:8.0.26
    container_name: iptracer-db
    restart: always
    volumes:
      - /:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: app
      MYSQL_PASSWOARD: app
    ports:
      - "3306:3306"
  app:
    depends_on:
      - db
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"